\documentclass[../../Main.tex]{subfiles}
\begin{document}
\section{流程控制}
流程控制控制了程序运行的步骤。流程控制包括顺序控制、条件控制和循环控制。顺序控制，顾名思义，就是按照代码的先后顺序，从上到下依次执行代码。

\subsection{脚本标签}
在Ren'Py中，我们可以使用label语句，用自定义的标签名声明一个程序点位。这些标签用于调用或者跳转，可以使用在Ren'Py脚本、Python函数及各类界面中。

\subsubsection{label 语句}
在游戏中，故事常常会有多个走向，这是我们就需要编写多个分支。如果剧情只围绕一个分支来讲述故事，那么一定是很枯燥的。同时，如果我们把所有的代码都写在一个label里，无疑会对编写与后期的维护造成不必要的麻烦。这时候，就需要定义多个 label。

label语句的基本语法为：
\begin{lstlisting}
label <标签名>(参数 1, 参数 2, ...):
    <语句 1>
    <语句 2>
    <语句 3>
    ...
\end{lstlisting}

当标签不接受参数时，可以省略小括号及里面的内容。
如下例子：
\begin{lstlisting}
label ch0_end:
    scene bg club_day
    "多么美好的一天啊！"
    return
\end{lstlisting}

\begin{Warning}
    通常在label语句末尾，我们都会使用return来返回到上一个调用栈（stack）。在这里您可以理解为回到之前执行的函数、label继续运行游戏。

    如果没有return语句，在执行完本label，Ren'Py会继续调用在本label定义之后的label。
\end{Warning}

label可以在不同的文件内定义。例如我们现在在game目录下创造一个名为script-ch0\_tasks.rpy的文件，并向这个文件中写入以下内容：
\begin{lstlisting}[caption=script-ch0\_tasks.rpy]
label ch0_monika:
    scene bg club_day
    show monika 1a at t11
    m "想好要做什么了吗？"
    return

label ch0_natsuki:
    scene bg club_day
    show natsuki 1a at t11
    n "不过，你知道怎么做小蛋糕吗？"
    return
\end{lstlisting}

此时，我们在ch0\_start标签中可以调用ch0\_monika与ch0\_natsuki标签。

\subsubsection{call语句与jump语句}

现在，让我们修改一下script-ch0.rpy中的内容：
\begin{lstlisting}[caption=script-ch0.rpy]
default n_aff = 0
default s_aff = 0
default demo = False

label ch0_start:
    scene bg club_day
    "{cps=20}快到{b}学园祭{/b}了。{/cps}{w=.5}{nw}"
    show monika 1a at l41 zorder 1
    m "各位！我们得开始准备了！"
    show sayori 1a at h42 zorder 1
    s "好耶！！！！"
    show natsuki 1a at t43 zorder 1
    n 2d "啊，我都等不及学园祭了。"
    n "肯定会很棒的！"
    show yuri 1a at s44 zorder 1
    y "..."
    scene bg club_day
    show monika 2a at t21 zorder 1
    show sayori 2a at t22 zorder 1
    m "那么，是时候来进行分工了。"
    m 4k "[player],你想要做什么? "

    if demo:
        "Demo 版剧情到此结束。"
        return

    menu:
        "做小蛋糕":
            s "夏树的小蛋糕最好吃了！"
            python:
                $ n_aff += 1
                $ m_aff -= 1
            call ch0_natsuki
        "布置教室":
            m "那我们可得抓紧时间了！"
            python:
                $ m_aff += 1
                $ n_aff -= 1
            call ch0_monika
    return
\end{lstlisting}

运行上述代码，我们会发现在玩家做出选择后，执行了在script-ch1\_tasks.rpy中的label中的内容。这就依赖于call语句和jump语句为我们提供的跳转功能了。

call语句和jump语句可以将程序跳转到一个指定的脚本标签处。

call与jump的区别在于，call语句相当于调用，在目标标签执行完毕后会回到当前标签。而jump相当于跳转，在目标标签执行完后将不会返回当前标签。

call语句和jump语句的语法如下：
\begin{lstlisting}
call/jump <标签名>
\end{lstlisting}

或者

\begin{lstlisting}
call/jump expression <label 表达式>
\end{lstlisting}

如下例：
\begin{lstlisting}
label ch0_start:
    scene bg club_day
    m "你现在正在主标签内。"
    $ today_winner = "sayori"
    call test_natsuki
    m "哦，你回来了？（跳转到 test_natsuki 标签后返回主标签。）"
    call expression "test_" + today_winner
    m "你刚刚又去哪里了？（跳转到 test_sayori 标签后再次返回主标签。）"
    jump no_way
    m "[player]，你还在吗？（这行不会被执行）"
    return

label test_natsuki:
    n "你跳转到了 test_natsuki 标签内。"
    return

label test_sayori:
    s "你跳转到了 test_sayori 标签内。"
    return

label no_way:
    y "好吧，看起来你回不去了。（因为使用了jump，所以你无法回到莫妮卡那里了）"
    return
\end{lstlisting}

运行上述代码，我们会发现我们一开始会运行ch0\_start标签中的内容。接着，我们会跳转到test\_natsuki标签内并运行代码，运行完成后我们会返回到ch0\_start标签中，随后再次跳转到test\_sayori标签内，然后我们又回到了ch0\_start标签中，最后，我们跳转到了no\_way标签中，并且不再返回ch0\_start标签，而是回到开始界面。

你或许注意到了，在ch0\_start中我们并没有直接使用call test\_sayori语句，而是使用了一个简单的表达式，然后把这个运算结果传递给了call。这就是expression选项的作用。使用expression选项，我们不用把标签名写死在程序里，可以立即运算表达式的结果并传递给call。这样做的好处是可以方便地在同一日的多个分支中跳转。

\subsection{if 判断}
大多数游戏中都具有多条剧情线。但面对一些只希望玩家触发多条剧情中的一条时，我们就可以利用if语句判断玩家的剧情线路。在Python和Ren'Py中，if语句的基本语法为：
\begin{lstlisting}
if <表达式>:
    <语句 1>
    <语句 2>
elif <表达式>:
    <语句 3>
elif <表达式>:
    <语句 4>
elif ...:
    ...
else:
    <语句 5>
\end{lstlisting}

每一个if语句中的表达式都应当返回一个True或False（见表\ref{table:4.1.5}）。结果为True时，将会执行if语句块中的代码，如果结果为False，Python就会忽略if语句块内的所有代码。

\begin{ExtraKnowledge}
    表达式也可以是一个数字、一个字符串、或定义了\_\_bool\_\_魔术方法的对象。

    不为0的数字、非空的字符串以及\_\_bool\_\_方法返回True的对象都会被视为True，而None、空字符串、0，当然还有False本身则会被视为False
\end{ExtraKnowledge}

如下例：

\begin{lstlisting}
if 1:
    print('1 is True.')

x = True

if x:
    print('x is True.')

if 1 + 1 == 2:
    print('Math is still correct.')
\end{lstlisting}

上述代码的输出结果为：
\begin{lstlisting}
1 is True.
x is True.
Math is still correct.
\end{lstlisting}

当表达式存在多个可能时，则可以使用elif语句。一个if语句中可以存在多个elif语句。如果想要在所有的if、elif语句都不成立时，额外执行一些代码，则可以使用else语句。

当if语句中的表达式为False时，会先判断elif子句是否成立，成立则执行该子句下的代码，否则继续判断其他elif子句，直到运行到else子句。如果运行到else子句时，if和elif语句的表达式中没有成立的均为False，那么就会执行else语句的内容。请注意，elif或else必须与if连用。如下例：

\begin{lstlisting}
if 1 + 1 != 2:
    print('Math crashes!')
elif 1 + 2 == 2:
    print('Math crashes again!')
else:
    print("It's OK. Nothing crazy happened.")
\end{lstlisting}

\subsection{循环}
循环允许我们重复执行一段代码而不需要编写更多的代码。Python中存在两种循环：while循环与for循环。

\subsubsection{while循环}
while循环是Python和Ren'Py中最简单的循环。它的语法结构如下：
\begin{lstlisting}
while <表达式>:
    <语句 1>
    <语句 2>
    ...
\end{lstlisting}

while循环的表达式与if循环的表达式一样。只有表达式为True时才会执行while内的语句。例如：

\begin{lstlisting}
i = 0
while i < 10:
    print(i)
    i += 1
\end{lstlisting}

输出结果为：
\begin{lstlisting}
0
1
2
3
4
5
6
7
8
9
\end{lstlisting}

\begin{Warning}
    请注意，一般表达式不为True，否则就会出现无限循环或死循环。如将上例中的i+= 1删去，就会导致i这个变量恒定为0，0又一定会小于10，那么该表达式就一定会返回True，使得程序卡死在while循环，无法运行下一个代码。在后文中我们将会介绍break和continue语句来打破或跳过循环。
\end{Warning}

\subsubsection{for循环\PyOnly }
for循环比while循环的使用方法更加丰富。它的语法结构如下：
\begin{lstlisting}
for <变量名> in <序列>:
    <语句 1>
    <语句 2>
    ...
\end{lstlisting}

这里的序列可以是列表、元组等可迭代对象。当序列中不再有变量后，for循环会停止运行。如下例：

\begin{lstlisting}
t1 = ('Sayori', 'Monika', 'Yuri', 'Natsuki')
l1 = [0, 0, 2, 0]

for i in t1:
    print(i)

for i in l1:
    print(i)
\end{lstlisting}

输出结果为：
\begin{lstlisting}
Sayori
Monika
Yuri
Natsuki
0
0
2
0
\end{lstlisting}

\begin{ExtraKnowledge}
    range函数是Python的内部函数之一，它可以为我们生成一个生成器（类似于列表，但比列表的性能更好）。使用range函数，我们可以快速生成一个从某数开始，按照一定规律排列到某数结束的一个生成器。如下例：
    \begin{lstlisting}
    for i in range(10):
        print(i)

    print("================================================")

    for i in range(10, 0, -1):
        print(i)
    \end{lstlisting}
    输出结果为：
    \begin{lstlisting}
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
    ================================================
    10
    9
    8
    7
    6
    5
    4
    3
    2
    1
    \end{lstlisting}

    上述第二个例子中的10就是起始数字，0则为截止数字，-1就是步长。range会从10开始，依次加上-1，即减去1，直到运算结果为0时停止。（请注意，截止数字不会包含在range所生成的生成器中）
\end{ExtraKnowledge}

在部分情况中，我们希望可以跳过循环或退出循环体，这时我们就可以使用break和continue语句了。break可以立即退出循环体，如下例：

\begin{lstlisting}
i = 0
while i < 10:
    print(i)
    i += 1
    if i > 5:
        break
print("End")
\end{lstlisting}

输出结果为：
\begin{lstlisting}
0
1
2
3
4
5
End
\end{lstlisting}

可以看到，在这个过程中i的值为0到5，虽然i<10此时依然成立，但由于while循环下编写了一个if判断，当i大于5时执行break语句，打破了循环，所以没有输出6、7、8、9

continue可以跳过当前的循环，如下例：

\begin{lstlisting}
for i in range(10):
    if i == 5:
        continue
    print(i)
\end{lstlisting}


输出结果为：
\begin{lstlisting}
0
1
2
3
4
6
7
8
9
\end{lstlisting}

可以看到输出结果中并没有5，这是由于for循环下的if语句判断当i等于5时，执行continue子句，continue子句会让后续代码被跳过，直接进入下一个循环，所以没有输出5。

同时，在Python中，循环也可以使用else语句。在while语句中的else语句会在while表达式为False时被执行。如下例：

\begin{lstlisting}
i = 0
while i <= 9:
    print(i)
    i += 1
else:
    print(i, " is bigger than 9")
\end{lstlisting}

输出结果为：
\begin{lstlisting}[language=C]
0
1
2
3
4
5
6
7
8
9
10 is bigger than 9
\end{lstlisting}

同时，请注意break导致的循环体退出不会执行else语句中的内容。

\subsection{错误和异常\PyOnly }
在Python中，不正常或语法错误的代码将会抛出异常。异常会使程序停止运行、崩溃、闪退等。常见的异常有：NameError（尝试使用一个未定义的变量）、IndexError（尝试访问在列表或元组范围外的索引）、TypeError（试图将两个不支持运算的类型进行运算）等。

为了处理这些异常，我们可以使用try-except语句。它的语法结构如下：
\begin{lstlisting}
try:
    <可能抛出错误的语句>
except <错误类型>:
    <当错误被捕获后的语句>
\end{lstlisting}

如下例子：

\begin{lstlisting}
try:
    x = 1 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero.')
\end{lstlisting}

输出结果为：
\begin{lstlisting}
Error: Cannot divide by zero.
\end{lstlisting}

进阶的语法包含finally从句或else从句。请注意，finally从句与else从句不可并存。

在try-except-finally中，无论try代码块中的代码是否抛出异常，finally从句中的代码都一定会被执行。try-except-finally的语法如下：
\begin{lstlisting}
try:
    <可能抛出错误的语句>
except <错误类型>:
    <当错误被捕获后的语句>
finally:
    <无论是否抛出错误都会执行的语句>
\end{lstlisting}

如下例子：

\begin{lstlisting}
div = 0
def func():
    global div
    return 1 / div

try:
    x = func()
except ZeroDivisionError:
    print('Error: Cannot divide by zero.')
finally:
    x = 10

print(x)

div = 10
try:
    x = func()
except ZeroDivisionError:
    print('Error: Cannot divide by zero.')
finally:
    x = 100
print(x)
\end{lstlisting}

输出结果为：
\begin{lstlisting}
Error: Cannot divide by zero.
10
100
\end{lstlisting}

try-except-else中，只有当try语句块中的内容没有抛出异常时，else中的内容才会被执行。try-except-else的语法如下：
\begin{lstlisting}
try:
    <可能抛出错误的语句>
except <错误类型>:
    <当错误被捕获后的语句>
else:
    <当没有错误被捕获时执行的语句>
\end{lstlisting}

如下例：

\begin{lstlisting}
try:
    x = 1 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero.')
else:
    print("The value of x is ", x)

try:
    x = 1 / 10
except ZeroDivisionError:
    print('Error: Cannot divide by zero.')
else:
    print("The value of x is ", x)
\end{lstlisting}

输出结果为：

\begin{lstlisting}
Error: Cannot divide by zero.
The value of x is 0.1
\end{lstlisting}
\end{document}